In [1]:
import numpy as np

arr = np.ones((4, 3), dtype="int")
print(arr)
print(arr.shape)
print(arr.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
(4, 3)
int64


In [2]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr2 = np.arange(1, 10)
print(arr2)


[1 2 3 4 5 6 7 8 9]


In [5]:
import numpy as np

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
import numpy as np
arr1 = np.arange(100)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [7]:
arr2 = np.arange(1,20)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
for i in range(5, 11): 
    print(i)

5
6
7
8
9
10


In [11]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [1]:
import numpy as np
print(np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3))


[[1 2 3]
 [4 5 6]]


In [23]:
#array attributes

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)     
print(arr.size) 
print(arr.dtype)  

2
6
int64


In [13]:
# array indexing
arr = np.array([10, 20, 30, 40])
print(arr[1])    
print(arr[-1])    

arr2 = np.array([[1, 2], [3, 4]])
print(arr2[0][1]) 

20
40
2


In [14]:
# reshape & arange
a = np.arange(1, 10)            
b = a.reshape(3, 3)             
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# arithmatic operation
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)    


[5 7 9]


In [16]:
# arithmatic operation
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x - y)     
print(x ** 2) 

[-3 -3 -3]
[1 4 9]


In [18]:
#self learning topic

arr = np.array([1, 3, 7, 2, 9])

print(np.argmax(arr))  


4


In [21]:
#self learning topic 

arr = np.array([1, 3, 7, 2, 9])

print(np.argmin(arr))   
print(np.linspace(0, 1, 5))
print(np.diff(arr)) 

0
[0.   0.25 0.5  0.75 1.  ]
[ 2  4 -5  7]
